# Generated by Django 6.0.1 on 2026-02-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0003_books_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
